#data_path: "./data/graph_features_text_no_cd.json"
vocab: ./data/ag_news/vocab.txt
data: ./data/ag_news/ag_content.txt
vocab_size: 0
head_num: 4
label_size: 4
has_dev: False
dev_split: 0.1
log: './data/ag_news/log/'
epoch: 5
batch_size: 64
param_init: 0.1
optim: 'adam'
learning_rate: 0.0005
max_grad_norm: 8
learning_rate_decay: 0.5
schedule: True
start_decay_at: 2
emb_size: 128
encoder_hidden_size: 128
num_layers: 6
bidirec: True
dropout: 0.1
max_sentence_len: 100
eval_interval: 500
save_interval: 5000
max_generator_batches: 32
